site_name: Reino Carpa
theme:
  name: material
  palette:
    primary: black
    accent: red
    
nav:
  - Inicio: index.md
  - Reglas: rules.md
  - Roles:
    - Aventurero: roles/adventurer.md
    - Mercenario: roles/mercenary.md
    - Guardia Real: roles/royal-guard.md